version: '3.9'
services:
  mongodb:
    image: mongo
    command: --logpath /var/log/mongodb/db.log
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - ./data:/data/db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=ACME-Explorer
  acme-explorer:
    build: .
    ports:
      - "${NODE_PORT}:8080"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
