openapi: 3.0.0
info:
  title: dataWarehouse
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /v2/dashboard:
    get:
      tags:
        - dataWarehouse
      summary: readDataWarehouse
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v2/dashboard/latest:
    get:
      tags:
        - dataWarehouse
      summary: readLatestDataWarehouse
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v2/dashboard/rebuild-period:
    patch:
      tags:
        - dataWarehouse
      summary: updateRebuildPeriod
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                period: 30
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v2/dashboard/spent-money-by-explorer:
    post:
      tags:
        - dataWarehouse
      summary: spentMoneyByExplorer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                explorer: 63ed27e96bb6772e5dab87ad
                period: M06
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v2/dashboard/explorers-by-spent-money:
    post:
      tags:
        - dataWarehouse
      summary: explorersBySpentMoney
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                period: M36
                theta: gte
                v: 1
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
