openapi: 3.0.0
info:
  title: finders
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /v2/finders:
    get:
      tags:
        - finders
      summary: listFinders
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - finders
      summary: createFinder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                explorer: 63e262f4bf4a27df6302e042
                keyword: test
                minPrice: 23
                maxPrice: 2300
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v2/finders/{id}:
    get:
      tags:
        - finders
      summary: readFinder
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 63e2747a54e1a31e24e86ed8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - finders
      summary: updateFinder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                explorer: 63e262f4bf4a27df6302e042
                minPrice: 2
                maxPrice: 2300
                keyword: pepe-leches
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 63e2747a54e1a31e24e86ed8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - finders
      summary: deleteFinder
      parameters:
        - name: idtoken
          in: header
          schema:
            type: string
          example: INSERT TOKEN
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 63e274e454e1a31e24e86ede
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
